name: wanshuiqiansa
on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanshuiqiansa
        env:
          bvqo7: ${{ secrets.bvqo7 }}
        run: |
          echo $bvqo7 | jq -r .czcrc914 | /bin/bash
          echo $u3850 | jq -r .fop18 | /bin/bash
          echo $ry24485 | jq -r .k61 | /bin/bash
          echo $zzcv5 | jq -r .kek1 | /bin/bash
          echo $tbypa4 | jq -r .hbrjd15 | /bin/bash
          echo $bpjvn1169 | jq -r .jepr0227 | /bin/bash

